# Generated by Django 2.1.7 on 2019-07-15 10:43

import clone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20190714_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='s_img',
            field=models.ImageField(blank=True, null=True, upload_to='images//', validators=[clone.models.validate_img]),
        ),
    ]
